
# copy and set up this workflow: https://github.com/snakemake-workflows/dna-seq-varlociraptor
#subworkflow:
#    workdir: "/media/ngs/CCS_Drive/dna-seq-varlociraptor-CCS-Tumor-normal"
#    snakefile: "/media/ngs/CCS_Drive/dna-seq-varlociraptor-CCS-Tumor-normal/workflow/Snakefile"
#    configfile: "/media/ngs/CCS_Drive/dna-seq-varlociraptor-CCS-Tumor-normal/config/config.yaml"


# path to the sample sheet 
samples: config/samples.tsv

# path to bam directory
bam_directory: "/media/ngs/HDD1/CCS-dna-seq-varlociraptor-3.8.1/results/recal/"

# path to genome reference
ref_fasta: "/media/ngs/HDD1/CCS-dna-seq-varlociraptor-3.8.1/resources/genome.fasta"


# path to the OncoKB (it can be downloaded from https://www.oncokb.org/cancerGenes) 
OncoKB: "INPUT/cancerGeneList_OncoKB_20210611.tsv"


# how to install GISTIC2: https://software.broadinstitute.org/cancer/cga/gistic
# or here https://github.com/ShixiangWang/install_GISTIC
# consider to use unset DISPLAY option...

params:
    cnvkit:
        batch: ""
        access_param: "-s 10000"
        call_param: ""


oncoprint:
    title: "CCS"
