# This scenario is templated with Jinja2 and rendered for each group (see sample sheet).
# A variable `samples` is available, holding the dataframe of
# the sample sheet, filtered to those samples contained in the group to be rendered.
# For example, this can be used to pass arbitrary column values (like the purity below),
# to the sample definitions.
# Note that sample names here must correspond to the alias column in the sample sheet.
species:
  heterozygosity: 0.001
  germline-mutation-rate: 1e-3
  ploidy:
    male:
      all: 2
      X: 1
      Y: 1
    female:
      all: 2
      X: 2
      Y: 0
  genome-size: 3.5e9

samples:
  tumor:
    sex: {{samples[samples["alias"] == "tumor"]["sex"][0]}}
    somatic-effective-mutation-rate: 1e-6
    inheritance:
      clonal:
        from: normal
        somatic: true
    contamination:
      by: normal
      fraction: {{ 1.0 - samples[samples["alias"] == "tumor"]["purity"][0] }}
  normal:
    sex: {{samples[samples["alias"] == "normal"]["sex"][0]}}
    somatic-effective-mutation-rate: 1e-6
    contamination:
      by: tumor
      fraction: 0.03

events:
  somatic_tumor_low: "tumor:]0.0,0.1[ & normal:0.0"
  somatic_tumor_medium: "tumor:[0.1,0.25[ & normal:0.0"
  somatic_tumor_high: "tumor:[0.25,1.0] & normal:0.0"
  somatic_normal: "normal:]0.0,0.5["
  germline_hom: "normal:1.0"
  germline_het: "normal:0.5"

