import glob
from os import path

import pandas as pd


from snakemake.utils import min_version
min_version("6.5.2")

container: "docker://continuumio/miniconda3"


configfile: "config/config.yaml"


samples = pd.read_csv(config["samples"], sep="\t", dtype={"sample_name": str, "target_bed": str}).set_index(["sample_name"], drop=False).sort_index()
SAMPLES = samples["sample_name"].unique()

#subworkflow dna_seq_varlociraptor:
#    workdir: config["subworkflow"]["workdir"]
#    snakefile:config["subworkflow"]["snakefile"]
#    configfile: config["subworkflow"]["configfile"]



rule all:
    input:
        "results/cnvkit/gistic.input.seg",
        "results/oncoprint/tumor_supressor_deletions_only.pdf",
        "results/oncoprint/oncogene_amplifications_only.pdf",
        "results/oncoprint/oncogene_vgp.pdf"




include: "rules/common.smk"
include: "rules/cnvkit.smk"
include: "rules/oncoprint.smk"